
export const fallbackPuttingDrills = [
  {
    id: 'putting-alignment-drill',
    title: 'Putting Alignment Drill',
    overview: 'Improve your alignment and stroke path consistency on the putting green.',
    category: 'Putting',
    focus: ['Alignment', 'Stroke Path', 'Consistency'],
    difficulty: 'Beginner',
    duration: '15-20 minutes',
    instruction1: 'Place alignment sticks or clubs on the ground to create a channel to putt through.',
    instruction2: 'Place a ball in the center and make putting strokes ensuring your putter stays on path.',
    instruction3: 'Focus on keeping your putter face square to the target line throughout the stroke.',
    common_mistake1: 'Moving your head during the stroke',
    common_mistake2: 'Breaking wrists during the putting stroke',
    pro_tip: 'Keep your eyes directly over the ball for best alignment perspective.'
  },
  {
    id: 'clock-face-putting-drill',
    title: 'Clock Face Putting Drill',
    overview: 'Improve distance control and confidence with short putts by practicing from all angles.',
    category: 'Putting',
    focus: ['Distance Control', 'Direction', 'Green Reading'],
    difficulty: 'Intermediate',
    duration: '20 minutes',
    instruction1: 'Place 12 balls in a circle around a hole, like numbers on a clock face, about 3 feet away.',
    instruction2: 'Start at 12 o\'clock and work your way around, trying to make each putt.',
    instruction3: 'If you miss a putt, start over from the beginning.',
    common_mistake1: 'Rushing through the drill without proper setup',
    common_mistake2: 'Failing to account for slope from different angles',
    pro_tip: 'Focus on your routine before each putt to build consistency.'
  },
  {
    id: 'ladder-putting-drill',
    title: 'Ladder Putting Drill',
    overview: 'Develop precise distance control by putting to multiple distances in sequence.',
    category: 'Putting',
    focus: ['Distance Control', 'Touch', 'Feel'],
    difficulty: 'Intermediate',
    duration: '15-20 minutes',
    instruction1: 'Place markers at 3, 6, 9, 12, and 15 feet from the hole.',
    instruction2: 'Putt three balls from each distance before moving to the next.',
    instruction3: 'Keep score of how many putts you make at each distance.',
    common_mistake1: 'Using the same stroke length for all distances',
    common_mistake2: 'Focusing too much on mechanics instead of feel',
    pro_tip: 'For longer putts, focus on getting the ball within a 3-foot circle of the hole.'
  },
  {
    id: 'gate-drill-putting',
    title: 'Gate Putting Drill',
    overview: 'Improve your putting accuracy and face control with this precision drill.',
    category: 'Putting',
    focus: ['Accuracy', 'Face Control', 'Starting Line'],
    difficulty: 'Intermediate',
    duration: '15 minutes',
    instruction1: 'Place two tees or coins on the green creating a gate slightly wider than your putter head.',
    instruction2: 'Position the gate about 6 inches in front of your ball on your intended line.',
    instruction3: 'Practice putting through the gate without hitting either tee.',
    common_mistake1: 'Opening or closing the putter face at impact',
    common_mistake2: 'Accelerating too quickly through impact',
    pro_tip: 'Start with a wider gate and gradually make it narrower as you improve.'
  },
  {
    id: 'lag-putting-drill',
    title: 'Lag Putting Distance Control Drill',
    overview: 'Master distance control for long putts to reduce three-putts.',
    category: 'Putting',
    focus: ['Distance Control', 'Speed', 'Feel'],
    difficulty: 'Advanced',
    duration: '20 minutes',
    instruction1: 'Place rings of tees at 3-foot intervals from 20-30 feet away from the hole.',
    instruction2: 'Practice hitting putts that stop within each ring.',
    instruction3: 'Focus on your pre-putt routine and distance control, not making the putt.',
    common_mistake1: 'Hitting the ball too hard on long putts',
    common_mistake2: 'Changing your stroke mechanic for different distances',
    pro_tip: 'Visualize the speed before each putt and commit to your stroke.'
  }
];
