/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AIAnalysis`; params?: Router.UnknownInputParams; } | { pathname: `/AIPracticePlans`; params?: Router.UnknownInputParams; } | { pathname: `/Auth`; params?: Router.UnknownInputParams; } | { pathname: `/ChallengeHistory`; params?: Router.UnknownInputParams; } | { pathname: `/ChallengeLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/ChallengeTracking`; params?: Router.UnknownInputParams; } | { pathname: `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/DrillLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/MyPracticePlans`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/RoundDetail`; params?: Router.UnknownInputParams; } | { pathname: `/RoundsList`; params?: Router.UnknownInputParams; } | { pathname: `/RoundTracking`; params?: Router.UnknownInputParams; } | { pathname: `/Subscription`; params?: Router.UnknownInputParams; } | { pathname: `/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AIAnalysis`; params?: Router.UnknownOutputParams; } | { pathname: `/AIPracticePlans`; params?: Router.UnknownOutputParams; } | { pathname: `/Auth`; params?: Router.UnknownOutputParams; } | { pathname: `/ChallengeHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/ChallengeLibrary`; params?: Router.UnknownOutputParams; } | { pathname: `/ChallengeTracking`; params?: Router.UnknownOutputParams; } | { pathname: `/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/DrillLibrary`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/MyPracticePlans`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/RoundDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/RoundsList`; params?: Router.UnknownOutputParams; } | { pathname: `/RoundTracking`; params?: Router.UnknownOutputParams; } | { pathname: `/Subscription`; params?: Router.UnknownOutputParams; } | { pathname: `/Welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AIAnalysis${`?${string}` | `#${string}` | ''}` | `/AIPracticePlans${`?${string}` | `#${string}` | ''}` | `/Auth${`?${string}` | `#${string}` | ''}` | `/ChallengeHistory${`?${string}` | `#${string}` | ''}` | `/ChallengeLibrary${`?${string}` | `#${string}` | ''}` | `/ChallengeTracking${`?${string}` | `#${string}` | ''}` | `/Dashboard${`?${string}` | `#${string}` | ''}` | `/DrillLibrary${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/MyPracticePlans${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/RoundDetail${`?${string}` | `#${string}` | ''}` | `/RoundsList${`?${string}` | `#${string}` | ''}` | `/RoundTracking${`?${string}` | `#${string}` | ''}` | `/Subscription${`?${string}` | `#${string}` | ''}` | `/Welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AIAnalysis`; params?: Router.UnknownInputParams; } | { pathname: `/AIPracticePlans`; params?: Router.UnknownInputParams; } | { pathname: `/Auth`; params?: Router.UnknownInputParams; } | { pathname: `/ChallengeHistory`; params?: Router.UnknownInputParams; } | { pathname: `/ChallengeLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/ChallengeTracking`; params?: Router.UnknownInputParams; } | { pathname: `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/DrillLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/MyPracticePlans`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/RoundDetail`; params?: Router.UnknownInputParams; } | { pathname: `/RoundsList`; params?: Router.UnknownInputParams; } | { pathname: `/RoundTracking`; params?: Router.UnknownInputParams; } | { pathname: `/Subscription`; params?: Router.UnknownInputParams; } | { pathname: `/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
